# Generated by Django 2.2.8 on 2020-03-24 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appkallawaya', '0002_auto_20200323_0517'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='cura',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='plant',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
