# Generated by Django 2.2.8 on 2020-03-24 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appkallawaya', '0003_auto_20200324_0037'),
    ]

    operations = [
        migrations.CreateModel(
            name='Malestares',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('description', models.CharField(default='', help_text='Adiciona observaciones/informacion', max_length=1200)),
            ],
        ),
    ]
