# Generated by Django 3.0.4 on 2020-03-25 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appkallawaya', '0004_malestares'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prueba',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_customer', models.BooleanField(default=False, verbose_name='Is customer')),
                ('is_seller', models.BooleanField(default=False, verbose_name='Is seller')),
                ('roles', models.CharField(choices=[('user', 'USER'), ('admin', 'ADMIN')], default='user', max_length=10)),
            ],
        ),
    ]
