# Generated by Django 3.0.4 on 2020-03-25 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appkallawaya', '0005_prueba'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Prueba',
        ),
    ]
