# Generated by Django 2.2.8 on 2020-03-25 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appkallawaya', '0005_auto_20200325_0020'),
        ('appkallawaya', '0007_post'),
    ]

    operations = [
    ]
