# Generated by Django 2.2.8 on 2020-03-26 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appkallawaya', '0008_merge_20200325_2310'),
    ]

    operations = [
        migrations.CreateModel(
            name='MalestaresTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='dolor de estomago', max_length=100)),
                ('description', models.CharField(default='dolor', help_text='Adiciona observaciones/informacion', max_length=1200)),
            ],
        ),
        migrations.CreateModel(
            name='Plant2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('description', models.CharField(default='', max_length=1500)),
                ('cura', models.CharField(default='', max_length=1500)),
                ('malestares2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appkallawaya.MalestaresTable')),
            ],
        ),
        migrations.DeleteModel(
            name='Malestares',
        ),
    ]
