# Generated by Django 2.2.8 on 2020-03-26 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appkallawaya', '0009_auto_20200326_2349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant2',
            name='malestares2',
        ),
        migrations.DeleteModel(
            name='MalestaresTable',
        ),
        migrations.DeleteModel(
            name='Plant2',
        ),
    ]
