# Generated by Django 2.2.8 on 2020-03-27 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appkallawaya', '0011_dolencias_planttotal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlantTotal',
        ),
    ]
