# Generated by Django 2.2.8 on 2020-03-27 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appkallawaya', '0012_delete_planttotal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Herb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('description', models.CharField(default='', max_length=1500)),
                ('cura', models.CharField(default='', max_length=1500)),
                ('dolencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appkallawaya.Dolencias')),
            ],
        ),
    ]
