# Generated by Django 2.2.8 on 2020-03-27 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appkallawaya', '0013_herb'),
    ]

    operations = [
        migrations.CreateModel(
            name='Molestia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('herb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appkallawaya.Plant')),
            ],
        ),
        migrations.RemoveField(
            model_name='herb',
            name='dolencia',
        ),
        migrations.DeleteModel(
            name='Dolencias',
        ),
        migrations.DeleteModel(
            name='Herb',
        ),
    ]
